name: logcat
description: Flutter plugin to get the system messages, stack traces etc using logcat command-line tool.
version: 1.1.0
homepage: https://github.com/nick-mpampamis/logcat

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  plugin:
    androidPackage: dev.pharsh.logcat
    pluginClass: LogcatPlugin
